{
    "amount": 12,
    "tasks": [
        "1. Customer brings defective computer",
        "2. CRS checks the defect",
        "3. CRS calculates repair cost",
        "4. Customer approves cost",
        "5. CRS checks hardware",
        "6. CRS repairs hardware",
        "7. CRS configures software",
        "8. CRS tests system functionality",
        "9. CRS detects errors",
        "10. Repeat process if errors",
        "11. Repair is finished",
        "12. Customer takes computer home"
    ]
}