{
    "amount": 13,
    "tasks": [
        "1. Guest calls manager",
        "2. Manager takes down order",
        "3. Manager submits order ticket",
        "4. Manager orders sommelier",
        "5. Manager assigns waiter",
        "6. Waiter readies cart",
        "7. Kitchen prepares order",
        "8. Sommelier prepares order",
        "9. Waiter delivers cart",
        "10. Waiter returns to station",
        "11. Waiter waits for billing",
        "12. Waiter debits guest account",
        "13. Waiter finishes billing/debiting"
    ]
}