The process starts with the "startevent" where the INQ transmits the transaction data request. This request is then checked by the IP in the "task" 1. After checking, the IP answers the question in the "task" 2. Finally, the process ends with the "endevent".