The process starts with a claims officer registering a claim. Then, the claims officer examines the claim. After that, there is an exclusive gateway denoted by "{x}". If the claim officer writes a settlement recommendation, it goes to a task where a senior claims officer checks the recommendation. Then, the senior claims officer marks the claim. Another exclusive gateway denoted by "{x}" follows. If everything is okay, the claim handling process proceeds to a task. If not, the senior claims officer sends the recommendation back. From there, it goes back to the previous exclusive gateway. If the claim handling process proceeds, it goes to an end event. If not, it goes back to the task where the claims officer examines the claim.