

The process starts when a guest calls and the manager takes down the order. The manager then submits an order ticket to the kitchen and gives an order to the sommelier. The manager assigns the order to the waiter, who readies the cart. The kitchen and the sommelier do their tasks, and the waiter delivers the cart and returns to the room service station. The waiter may wait to do the billing or debit the guest account, depending on whether there are any other orders. The process ends when the waiter has finished the billing or debiting.