{
    "amount": 11,
    "tasks": [
        "1. Customer brings defective computer",
        "2. CSR checks the defect",
        "3. CSR provides repair cost",
        "4. Customer decides on cost",
        "5. Customer takes computer home (if cost not acceptable)",
        "6. Checking and repairing hardware",
        "7. Checking and configuring software",
        "8. System functionality test",
        "9. Cost reassessment (if error detected)",
        "10. Repair declared finished",
        "11. Process ends"
    ]
}