{
    "amount": 13,
    "tasks": [
        "1. Guest places order",
        "2. Manager takes order",
        "3. Manager submits order ticket",
        "4. Manager assigns order to sommelier",
        "5. Manager assigns order to waiter",
        "6. Kitchen prepares order",
        "7. Sommelier prepares order",
        "8. Waiter readies the cart",
        "9. Waiter delivers order",
        "10. Waiter returns to station",
        "11. Waiter waits for billing",
        "12. Waiter debits guest's account",
        "13. Billing is completed."
    ]
}