{
    "amount": 15,
    "tasks": [
        "1. Guest places order",
        "2. Manager takes order",
        "3. Manager submits order ticket",
        "4. Manager assigns order to waiter",
        "5. Manager gives order to sommelier",
        "6. Kitchen starts preparing order",
        "7. Sommelier starts preparing order",
        "8. Waiter readies the cart",
        "9. Kitchen completes order",
        "10. Sommelier completes order",
        "11. Waiter delivers cart to guest",
        "12. Waiter returns to service station",
        "13. Waiter waits for next order",
        "14. Waiter debits guest account",
        "15. Billing is done."
    ]
}