

Guest calls, manager takes down the order, submits an order ticket to the kitchen, gives an order to the sommelier, assigns the order to the waiter, the kitchen and the sommelier do their tasks, the waiter readies the cart, delivers the cart, returns to the room service station, and may wait to do the billing or debit the guest account.