{
    "amount": 11,
    "tasks": [
        "1. \"Startevent\" by MPON",
        "2. Dismissal sent by MPON",
        "3. Dismissal review by MPOO",
        "4. Exclusive gateway reached",
        "5. MPOO opposes dismissal",
        "6. Task moves to another task",
        "7. MPOO confirms dismissal",
        "8. Task moves to next gateway",
        "9. Task goes to next task",
        "10. Reaching another exclusive gateway",
        "11. \"Endevent\" reached."
    ]
}