{
    "amount": 9,
    "tasks": [
        "1. \"Startevent\" sends dismissal",
        "2. MSPO reviews dismissal",
        "3. Exclusive gateway \"{x}\"",
        "4. Task if dismissal rejected",
        "5. Task if dismissal confirmed",
        "6. Exclusive gateway \"{x}\"",
        "7. Process goes to endevent",
        "8. Process returns to task",
        "9. Process ends with \"endevent\""
    ]
}