{
    "amount": 17,
    "tasks": [
        "1. Guest places order",
        "2. Manager takes order",
        "3. Manager submits order ticket",
        "4. Manager assigns order",
        "5. Kitchen starts task",
        "6. Sommelier starts task",
        "7. Waiter readies cart",
        "8. Kitchen completes task",
        "9. Sommelier completes task",
        "10. Waiter delivers cart",
        "11. Waiter returns to station",
        "12. Waiter waits for billing",
        "13. Waiter does billing",
        "14. Waiter debits guest's account",
        "15. Process continues with order",
        "16. Process ends if no orders",
        "17. Process ends with end event."
    ]
}