{
    "amount": 12,
    "tasks": [
        "1. Guest calls",
        "2. Manager takes order",
        "3. Submits order ticket",
        "4. Gives order to sommelier",
        "5. Assigns order to waiter",
        "6. Kitchen prepares order",
        "7. Sommelier prepares drinks",
        "8. Waiter readies cart",
        "9. Delivers the cart",
        "10. Returns to station",
        "11. Waits for billing",
        "12. Debits guest account"
    ]
}