{
    "amount": 9,
    "tasks": [
        "1. Register claim",
        "2. Examine claim",
        "3. Write settlement recommendation",
        "4. Send recommendation to senior",
        "5. Senior checks recommendation",
        "6. Mark claim",
        "7. Accept recommendation",
        "8. Proceed claim handling",
        "9. Send back recommendation"
    ]
}